name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd devind-rich-text-editor install
      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd devind-rich-text-editor lint

  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd devind-rich-text-editor install
      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd devind-rich-text-editor test

  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd devind-rich-text-editor install --immutable --immutable-cache --check-cache
      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd devind-rich-text-editor build
      - name: Post Build
        working-directory: ./devind-rich-text-editor
        run: |
          sudo cp -p package.json dist/
          sudo cp -r -p node_modules dist/
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
